apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rsgrafanadashboards.monitoring.com
spec:
  group: monitoring.com
  names:
    kind: RSGrafanaDashboard
    plural: rsgrafanadashboards
    singular: rsgrafanadashboard
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                json:
                  type: string
              type: object
            status:
              properties:
                lastSyncedChecksum:
                  type: string
                message:
                  type: string
                observedGeneration:
                  type: integer
                state:
                  enum:
                    - ERROR
                    - SYNCED
                  type: string
                uid:
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
